source 'https://github.com/CocoaPods/Specs'

xcodeproj 'GizouTests'
workspace '../Gizou'
inhibit_all_warnings!

def import_pods
	pod 'Specta', '~> 0.3.2'
  	pod 'Expecta', '~> 0.3.1'
  	pod 'Gizou', :path => '../'
end

target :ios do
  	platform :ios, '7.0'
  	link_with 'iostests'
  	import_pods
end

target :osx do
  	platform :osx, '10.7'
  	link_with 'osxtests'
  	import_pods
end
